### ISSUE TITLE
Library does not support XBOX 360 Controller Under Linux

### ISSUE THREAD

**Issue by ryanteck** [kallaspriit/HTML5-JavaScript-Gamepad-Controller-Library#8]
The Library fails to detect the XBOX 360 Gamepad as an XBOX gamepad and supports it as an unknown controller.

Here's the ID Info. Dumped through Chrome 26.0.1410.63.

Unsupported controller connected 
Gamepad {buttons: Array[17], axes: Array[4], timestamp: 1351764, index: 0, id: "©Microsoft Corporation Controller (STANDARD GAMEPAD Vendor: 045e Product: 028e)"…}
axes: Array[4]
0: 0.08609271794557571
1: -0.056611835956573486
2: 0.013000885024666786
3: 0.08087404817342758
length: 4
**proto**: Array[0]
buttons: Array[17]
0: 0
1: 0
2: 0
3: 0
4: 0
5: 0
6: 0
7: 0
8: 0
9: 0
10: 0
11: 0
12: 0
13: 0
14: 0
15: 0
16: 0
length: 17
**proto**: Array[0]
id: "©Microsoft Corporation Controller (STANDARD GAMEPAD Vendor: 045e Product: 028e)"
index: 0
timestamp: 1351764
type: "unsupported"
**proto**: Gamepad

This is using an official gamepad connected via USB.

**Comment by AnachronicNomad** [comment]
Did you test this with Chromium or any of the Beta or Dev channels of Chrome? Other projects similar to this one have relayed this kind of problem upstream as a browser problem.

**Comment by ryanteck** [comment]
I don't beleive so (No beta or dev on the end of chrome. Actually tested with chrome instead of chromium).

**Comment by AnachronicNomad** [comment]
Take a look at these. I'll try to test with all of them when I arrive home. Linux distro Beta/Dev channels are at the bottom of the list. 
http://www.chromium.org/getting-involved/dev-channel
OR
https://www.google.com/intl/en/chrome/browser/beta.html

**Comment by JakeChampion** [comment]
Seems the version that was used was 26 which was the stable release at the
time according to http://googlechromereleases.blogspot.com/
I would recommend trying the beta or dev versions and see if this issue was
resolved by the browser devs as suggested by fifthparallel.

Report back on the results. If it didnt get detected we then know to look
into this library and not the api itself.

**Comment by kallaspriit** [comment]
Well take a look at _resolveControllerType(), XBOX controllers are expected to contain either "xbox" or "360" in their name. I guess it could be made to detect this controller or perhaps to default to certain configuration such as the XBOX one.

**Comment by dertseha** [comment]
heya, @ryanteck - may I ask you to retest it with the newest master branch?
The code supports now any gamepad to best effort. If there is no specific mapping, the library reverts to the spec-defaults, which the XBOX controller adheres to; But since I don't have such a controller, can you do the verification?

**Comment by ryanteck** [comment]
Yeah all working fine now thanks ;D
